# Rustfmt configuration for Nebuchadnezzar
# Scientific computing projects often have long expressions and complex formulas

# Code style
edition = "2021"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Line length - slightly longer for scientific formulas
max_width = 100
comment_width = 80
wrap_comments = true

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Functions and control flow
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
indent_style = "Block"

# Expressions - important for scientific computing
overflow_delimited_expr = true
combine_control_expr = true
struct_field_align_threshold = 20
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50

# Whitespace
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false

# Misc
remove_nested_parens = true
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
format_strings = false  # Keep scientific notation and formulas intact
format_macro_matchers = true
format_macro_bodies = true

# Stability - use stable features only
unstable_features = false

# Specific to scientific computing
# Allow longer lines for mathematical expressions
use_field_init_shorthand = true
force_explicit_abi = true
condense_wildcard_suffixes = true 